### ISSUE TITLE
[FEATURE] Hope to add networking function

### ISSUE THREAD

**Issue by zhengkunwang223** [wanghe-fit2cloud/1Panel#2]
### 1Panel 版本

v2.0

### 请描述您的需求或者改进建议

希望增加组网功能

### 请描述你建议的实现方案

希望增加组网功能

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### 1Panel version

v2.0

### Please describe your needs or suggestions for improvements

Hope to add networking function

### Please describe your proposed implementation

Hope to add networking function

### Additional Information

_No response_
